// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLv79N6k2p2c8hDWSUZ0rm0bXPNa79C5U',
    appId: '1:607024005139:web:6aabce81c0566abe6b7fe6',
    messagingSenderId: '607024005139',
    projectId: 'auth-40702',
    authDomain: 'auth-40702.firebaseapp.com',
    storageBucket: 'auth-40702.firebasestorage.app',
    measurementId: 'G-N65H38YXHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyG16IfLAC9JL9ITk2BM__FLd4nT5rg1w',
    appId: '1:607024005139:android:5f308e35375709276b7fe6',
    messagingSenderId: '607024005139',
    projectId: 'auth-40702',
    storageBucket: 'auth-40702.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQF7z2JSwwI44TGtQ1_KOD-etlkoMF4Jg',
    appId: '1:607024005139:ios:860d0fde5f8aa9606b7fe6',
    messagingSenderId: '607024005139',
    projectId: 'auth-40702',
    storageBucket: 'auth-40702.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQF7z2JSwwI44TGtQ1_KOD-etlkoMF4Jg',
    appId: '1:607024005139:ios:860d0fde5f8aa9606b7fe6',
    messagingSenderId: '607024005139',
    projectId: 'auth-40702',
    storageBucket: 'auth-40702.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLv79N6k2p2c8hDWSUZ0rm0bXPNa79C5U',
    appId: '1:607024005139:web:69f331da546788b16b7fe6',
    messagingSenderId: '607024005139',
    projectId: 'auth-40702',
    authDomain: 'auth-40702.firebaseapp.com',
    storageBucket: 'auth-40702.firebasestorage.app',
    measurementId: 'G-VFJYM1PNYH',
  );
}
